# Generated by Django 5.1 on 2025-04-23 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_uuid', models.UUIDField(default=uuid.uuid4, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='img/projects/')),
                ('btn1_text', models.CharField(max_length=50)),
                ('btn1_url', models.URLField(blank=True, null=True)),
                ('btn2_text', models.CharField(max_length=50)),
                ('btn2_url', models.URLField(blank=True, null=True)),
                ('prj_value', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('network', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=110, null=True)),
                ('region', models.CharField(blank=True, max_length=110, null=True)),
                ('region_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_name', models.CharField(blank=True, max_length=110, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('continent_code', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, max_length=60, null=True)),
                ('utc_offset', models.CharField(blank=True, max_length=10, null=True)),
                ('org', models.CharField(blank=True, max_length=300, null=True)),
                ('asn', models.CharField(blank=True, max_length=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('languages', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contact')),
            ],
        ),
    ]
