# Generated by Django 5.1 on 2024-09-20 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_ipaddressinfo_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ip_address_info',
        ),
        migrations.AddField(
            model_name='ipaddressinfo',
            name='contact',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.contact'),
        ),
    ]
