# Generated by Django 5.1 on 2026-03-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_technology_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='technology',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='technology_logos/'),
        ),
        migrations.AddField(
            model_name='technology',
            name='logo_type',
            field=models.CharField(choices=[('image', 'Image'), ('svg', 'SVG')], default='image', max_length=20),
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectlink',
            name='link_type',
            field=models.CharField(choices=[('website', 'Website'), ('github', 'GitHub'), ('documentation', 'Documentation'), ('demo', 'Live Demo'), ('demo_video', 'Demo Video'), ('other', 'Other')], default='website', max_length=20),
        ),
        migrations.AlterField(
            model_name='technology',
            name='svg',
            field=models.TextField(blank=True, help_text='Inline SVG markup or SVG path/URL', null=True),
        ),
    ]
