# Generated by Django 5.1 on 2024-09-27 15:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_contact_ip_address_info_ipaddressinfo_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='auth_uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
