# Generated by Django 5.1 on 2026-03-19 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_technology_options_technology_logo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('achievement_type', models.CharField(choices=[('award', 'Award'), ('certification', 'Certification'), ('recognition', 'Recognition'), ('competition', 'Competition'), ('publication', 'Publication'), ('milestone', 'Milestone'), ('other', 'Other')], default='other', max_length=20)),
                ('issuer', models.CharField(blank=True, help_text="Org/person who gave the award e.g. 'Google', 'Harvard'", max_length=200)),
                ('short_description', models.CharField(max_length=180)),
                ('full_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, help_text='Badge, certificate screenshot, trophy photo', null=True, upload_to='achievements/')),
                ('image_alt', models.CharField(blank=True, max_length=120)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on hero/highlights section')),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectlink',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements_links', to='main.achievement'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievements_media', to='main.achievement'),
        ),
    ]
