# Generated by Django 5.1 on 2024-09-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_contact_auth_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('btn1_text', models.CharField(max_length=50)),
                ('btn1_url', models.URLField()),
                ('btn2_text', models.CharField(max_length=50)),
                ('btn2_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
