# Generated by Django 5.1 on 2026-03-21 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievement_projectlink_achievement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlink',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='projectmedia',
            name='achievement',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
