# Generated by Django 5.1 on 2024-09-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='btn1_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='btn2_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
