# Generated by Django 5.1 on 2024-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_project_btn1_url_alter_project_btn2_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prj_value',
            field=models.IntegerField(default=5),
        ),
    ]
